require("ohpxho.plugins-setup")
require("ohpxho.core.options")
require("ohpxho.core.keymaps")
require("ohpxho.core.colorscheme")
require("ohpxho.plugins.comment")
require("ohpxho.plugins.nvim-tree")
require("ohpxho.plugins.lualine")
require("ohpxho.plugins.telescope")
require("ohpxho.plugins.nvim-cmp")
require("ohpxho.plugins.lsp.mason")
require("ohpxho.plugins.lsp.lspsaga")
require("ohpxho.plugins.lsp.lspconfig")
require("ohpxho.plugins.autopairs")
require("ohpxho.plugins.treesitter")
require("ohpxho.plugins.gitsigns")
require("ohpxho.plugins.web-devicons")
require("ohpxho.plugins.conform")

vim.opt.wrap = true
vim.opt.linebreak = true
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
